<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fusource;../../packager/units/$(CPU_TARGET)-$(OS_TARGET);../BaseUtils/lib/$(CPU_TARGET)-$(OS_TARGET);../../lcl/units/$(CPU_TARGET)-$(OS_TARGET);../../lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../BaseControls/lib/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../BaseIdeintf/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);. -Fisource  -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -dLCL -dLCL$(LCL_PLATFORM) pl_bgrabitmap.pas"/>
</CONFIG>
